<?php
$wo["site_pages"]         = array(
    "home",
    "welcome",
    "activate",
    "search",
    "timeline",
    "pages",
    "page",
    "groups",
    "group",
    "create-group",
    "group-setting",
    "create-page",
    "setting",
    "page-setting",
    "messages",
    "logout",
    "404",
    "post",
    "games",
    "saved-posts",
    "hashtag",
    "terms",
    "contact-us",
    "albums",
    "album",
    "game",
    "go_pro",
    "upgraded",
    "oops",
    "user_activation",
    "boosted-pages",
    "boosted-posts",
    "video-call",
    "read-blog",
    "blog",
    "My-Blogs",
    "edit-blog",
    "create_blog",
    "developers",
    "ads",
    "password-reset",
    "admin-cp",
    "admincp",
    "adminPages",
    "start-up",
    "activated",
    "ads-create",
    "app",
    "messages",
    "terms",
    "video-call",
    "video-call-api",
    "post",
    "game",
    "upgraded",
    "get_news_feed",
    "new-game",
    "go-pro",
    "oops",
    "user-activation",
    "hashtag",
    "follow-requests",
    "404",
    "register",
    "confirm-sms",
    "forgot-password",
    "activate",
    "pages",
    "create-group",
    "create-page",
    "logout",
    "contact-us",
    "setting",
    "messages",
    "albums",
    "album",
    "products",
    "my-products",
    "blogs",
    "sharer",
    "app_api",
    "api_request",
    "authorize",
    "advertise"
);
$wo["feelingIcons"]       = array(
    "happy" => "smile",
    "loved" => "heart-eyes",
    "sad" => "disappointed",
    "so_sad" => "sob",
    "angry" => "angry",
    "confused" => "confused",
    "smirk" => "smirk",
    "broke" => "broken-heart",
    "expressionless" => "expressionless",
    "cool" => "sunglasses",
    "funny" => "joy",
    "tired" => "tired-face",
    "lovely" => "heart",
    "blessed" => "innocent",
    "shocked" => "scream",
    "sleepy" => "sleeping",
    "pretty" => "relaxed",
    "bored" => "unamused"
);
$emo                      = array(
    ":)" => "smile",
    "(&lt;" => "joy",
    "**)" => "relaxed",
    ":p" => "stuck-out-tongue-winking-eye",
    ":_p" => "stuck-out-tongue",
    "B)" => "sunglasses",
    ";)" => "wink",
    ":D" => "grin",
    "/_)" => "smirk",
    "0)" => "innocent",
    ":_(" => "cry",
    ":__(" => "sob",
    ":(" => "disappointed",
    ":*" => "kissing-heart",
    "&lt;3" => "heart",
    "&lt;/3" => "broken-heart",
    "*_*" => "heart-eyes",
    "&lt;5" => "star",
    ":o" => "open-mouth",
    ":0" => "scream",
    "o(" => "anguished",
    "-_(" => "unamused",
    "x(" => "angry",
    "X(" => "rage",
    "-_-" => "expressionless",
    ":-/" => "confused",
    ":|" => "neutral-face",
    "!_" => "exclamation",
    ":|" => "neutral-face",
    ":|" => "neutral-face",
    ":yum:" => "yum",
    ":triumph:" => "triumph",
    ":imp:" => "imp",
    ":hear_no_evil:" => "hear-no-evil",
    ":alien:" => "alien",
    ":yellow_heart:" => "yellow-heart",
    ":sleeping:" => "sleeping",
    ":mask:" => "mask",
    ":no_mouth:" => "no-mouth",
    ":weary:" => "weary",
    ":dizzy_face:" => "dizzy-face",
    ":man:" => "man",
    ":woman:" => "woman",
    ":boy:" => "boy",
    ":girl:" => "girl",
    ":оlder_man:" => "older-man",
    ":оlder_woman:" => "older-woman",
    ":cop:" => "cop",
    ":dancers:" => "dancers",
    ":speak_no_evil:" => "speak-no-evil",
    ":lips:" => "lips",
    ":see_no_evil:" => "see-no-evil",
    ":dog:" => "dog",
    ":bear:" => "bear",
    ":rose:" => "rose",
    ":gift_heart:" => "gift-heart",
    ":ghost:" => "ghost",
    ":bell:" => "bell",
    ":video_game:" => "video-game",
    ":soccer:" => "soccer",
    ":books:" => "books",
    ":moneybag:" => "moneybag",
    ":mortar_board:" => "mortar-board",
    ":hand:" => "hand",
    ":tiger:" => "tiger",
    ":elephant:" => "elephant",
    ":scream_cat:" => "scream-cat",
    ":monkey:" => "monkey",
    ":bird:" => "bird",
    ":snowflake:" => "snowflake",
    ":sunny:" => "sunny",
    ":оcean:" => "ocean",
    ":umbrella:" => "umbrella",
    ":hibiscus:" => "hibiscus",
    ":tulip:" => "tulip",
    ":computer:" => "computer",
    ":bomb:" => "bomb",
    ":gem:" => "gem",
    ":ring:" => "ring"
);
$wo["countries"]          = array(
    "united-states" => "United States",
    "china" => "China",
    "india" => "India",
    "iran" => "Iiran",
    "japan" => "japan",
    "turkey" => "Turkey",
    "russia" => "Russia",
    "france" => "France",
    "united-kingdom" => "United Kingdom"
);

$emo_full                 = array(
    ":)" => "🙂",
    "(&lt;" => "😂",
    "**)" => "😊",
    ":p" => "😛",
    ":_p" => "😜",
    "B)" => "😎",
    ";)" => "😉",
    ":D" => "😁",
    "/_)" => "smirk",
    "0)" => "innocent",
    ":_(" => "cry",
    ":__(" => "sob",
    ":(" => "disappointed",
    ":*" => "kissing-heart",
    "&lt;3" => "heart",
    "&lt;/3" => "broken-heart",
    "*_*" => "heart-eyes",
    "&lt;5" => "star",
    ":o" => "open-mouth",
    ":0" => "scream",
    "o(" => "anguished",
    "-_(" => "unamused",
    "x(" => "angry",
    "X(" => "rage",
    "-_-" => "expressionless",
    ":-/" => "confused",
    ":|" => "neutral-face",
    "!_" => "exclamation",
    ":|" => "neutral-face"
);
$wo["footer_pages"]       = array(
    "terms",
    "oops",
    "messages",
    "start_up",
    "404",
    "search",
    "admin",
    "user_activation",
    "upgraded",
    "go_pro",
    "video",
    "custom_page",
    "products",
    "read-blog",
    "blog",
    "My-Blogs",
    "edit-blog",
    "create_blog",
    "developers",
    "movies",
    "ads",
    "setting",
    "contact-us",
    "advertise",
    "jobs",
    "friends_nearby",
    "common_things",
    "events",
    "my_groups",
    "suggested_groups",
    "joined_groups",
    "my_albums",
    "my_products",
    "game",
    "funding",
    "jobs",
    "nearby_business",
    "customer_order",
    "purchased",
    "orders",
    "order",
    "checkout"
);
$wo["css_file_header"]    = "
<style>
.navbar-default {
   height:45px !important;
   display: block !important;
   visibility: visible !important;
}
</style>
";
$colors                   = $wo["colors"] = shuffle_assoc(array(
    "#b582af",
    "#a84849",
    "#fc9cde",
    "#f9c270",
    "#70a0e0",
    "#56c4c5",
    "#51bcbc",
    "#f33d4c",
    "#a1ce79",
    "#a085e2",
    "#ed9e6a",
    "#2b87ce",
    "#f2812b",
    "#0ba05d",
    "#f9a722",
    "#8ec96c",
    "#01a5a5",
    "#5462a5",
    "#609b41",
    "#ff72d2",
    "#008484",
    "#c9605e",
    "#aa2294",
    "#056bba",
    "#0e71ea"
));
$wo["family"]             = array(
    1 => "long term",
    2 => "short term",
    3 => "current",
);
$ad_media_types           = array(
    "video/mp4",
    "video/mov",
    "video/mpeg",
    "video/flv",
    "video/avi",
    "video/webm",
    "video/quicktime",
    "image/png",
    "image/jpeg",
    "image/gif"
);
$wo["stripe_currency"]    = array(
    "USD",
    "EUR",
    "AUD",
    "BRL",
    "CAD",
    "CZK",
    "DKK",
    "HKD",
    "HUF",
    "ILS",
    "JPY",
    "MYR",
    "MXN",
    "TWD",
    "NZD",
    "NOK",
    "PHP",
    "PLN",
    "RUB",
    "SGD",
    "SEK",
    "CHF",
    "THB",
    "GBP"
);
$wo["paypal_currency"]    = array(
    "USD",
    "EUR",
    "AUD",
    "BRL",
    "CAD",
    "CZK",
    "DKK",
    "HKD",
    "HUF",
    "INR",
    "ILS",
    "JPY",
    "MYR",
    "MXN",
    "TWD",
    "NZD",
    "NOK",
    "PHP",
    "PLN",
    "GBP",
    "RUB",
    "SGD",
    "SEK",
    "CHF",
    "THB"
);
$wo["2checkout_currency"] = array(
    "USD",
    "EUR",
    "AED",
    "AFN",
    "ALL",
    "ARS",
    "AUD",
    "AZN",
    "BBD",
    "BDT",
    "BGN",
    "BMD",
    "BND",
    "BOB",
    "BRL",
    "BSD",
    "BWP",
    "BYN",
    "BZD",
    "CAD",
    "CHF",
    "CLP",
    "CNY",
    "COP",
    "CRC",
    "CZK",
    "DKK",
    "DOP",
    "DZD",
    "EGP",
    "FJD",
    "GBP",
    "GTQ",
    "HKD",
    "HNL",
    "HRK",
    "HUF",
    "IDR",
    "ILS",
    "INR",
    "JMD",
    "JOD",
    "JPY",
    "KES",
    "KRW",
    "KWD",
    "KZT",
    "LAK",
    "LBP",
    "LKR",
    "LRD",
    "MAD",
    "MDL",
    "MMK",
    "MOP",
    "MRO",
    "MUR",
    "MVR",
    "MXN",
    "MYR",
    "NAD",
    "NGN",
    "NIO",
    "NOK",
    "NPR",
    "NZD",
    "OMR",
    "PEN",
    "PGK",
    "PHP",
    "PKR",
    "PLN",
    "PYG",
    "QAR",
    "RON",
    "RSD",
    "RUB",
    "SAR",
    "SBD",
    "SCR",
    "SEK",
    "SGD",
    "SYP",
    "THB",
    "TND",
    "TOP",
    "TRY",
    "TTD",
    "TWD",
    "UAH",
    "UYU",
    "VND",
    "VUV",
    "WST",
    "XCD",
    "XOF",
    "YER",
    "ZAR"
);
$wo["regx_attr"]          = '/(onclick=["](.*?)["]|onclick=[\'](.*?)[\']|onafterprint=["](.*?)["]|onafterprint=[\'](.*?)[\']|onbeforeprint=["](.*?)["]|onbeforeprint=[\'](.*?)[\']|onbeforeunload=["](.*?)["]|onbeforeunload=[\'](.*?)[\']|onerror=["](.*?)["]|onerror=[\'](.*?)[\']|onhashchange=["](.*?)["]|onhashchange=[\'](.*?)[\']|onload=["](.*?)["]|onload=[\'](.*?)[\']|onmessage=["](.*?)["]|onmessage=[\'](.*?)[\']|onoffline=["](.*?)["]|onoffline=[\'](.*?)[\']|ononline=["](.*?)["]|ononline=[\'](.*?)[\']|onpagehide=["](.*?)["]|onpagehide=[\'](.*?)[\']|onpageshow=["](.*?)["]|onpageshow=[\'](.*?)[\']|onpopstate=["](.*?)["]|onpopstate=[\'](.*?)[\']|onresize=["](.*?)["]|onresize=[\'](.*?)[\']|onstorage=["](.*?)["]|onstorage=[\'](.*?)[\']|onunload=["](.*?)["]|onunload=[\'](.*?)[\']|onblur=["](.*?)["]|onblur=[\'](.*?)[\']|onchange=["](.*?)["]|onchange=[\'](.*?)[\']|oncontextmenu=["](.*?)["]|oncontextmenu=[\'](.*?)[\']|onfocus=["](.*?)["]|onfocus=[\'](.*?)[\']|oninput=["](.*?)["]|oninput=[\'](.*?)[\']|oninvalid=["](.*?)["]|oninvalid=[\'](.*?)[\']|onreset=["](.*?)["]|onreset=[\'](.*?)[\']|onsearch=["](.*?)["]|onsearch=[\'](.*?)[\']|onselect=["](.*?)["]|onselect=[\'](.*?)[\']|onsubmit=["](.*?)["]|onsubmit=[\'](.*?)[\']|onkeydown=["](.*?)["]|onkeydown=[\'](.*?)[\']|onkeypress=["](.*?)["]|onkeypress=[\'](.*?)[\']|onkeyup=["](.*?)["]|onkeyup=[\'](.*?)[\']|ondblclick=["](.*?)["]|ondblclick=[\'](.*?)[\']|onmousedown=["](.*?)["]|onmousedown=[\'](.*?)[\']|onmousemove=["](.*?)["]|onmousemove=[\'](.*?)[\']|onmouseout=["](.*?)["]|onmouseout=[\'](.*?)[\']|onmouseover=["](.*?)["]|onmouseover=[\'](.*?)[\']|onmouseup=["](.*?)["]|onmouseup=[\'](.*?)[\']|onmousewheel=["](.*?)["]|onmousewheel=[\'](.*?)[\']|onwheel=["](.*?)["]|onwheel=[\'](.*?)[\']|ondrag=["](.*?)["]|ondrag=[\'](.*?)[\']|ondragend=["](.*?)["]|ondragend=[\'](.*?)[\']|ondragenter=["](.*?)["]|ondragenter=[\'](.*?)[\']|ondragleave=["](.*?)["]|ondragleave=[\'](.*?)[\']|ondragover=["](.*?)["]|ondragover=[\'](.*?)[\']|ondragstart=["](.*?)["]|ondragstart=[\'](.*?)[\']|ondrop=["](.*?)["]|ondrop=[\'](.*?)[\']|onscroll=["](.*?)["]|onscroll=[\'](.*?)[\']|oncopy=["](.*?)["]|oncopy=[\'](.*?)[\']|oncut=["](.*?)["]|oncut=[\'](.*?)[\']|onpaste=["](.*?)["]|onpaste=[\'](.*?)[\']|onabort=["](.*?)["]|onabort=[\'](.*?)[\']|oncanplay=["](.*?)["]|oncanplay=[\'](.*?)[\']|oncanplaythrough=["](.*?)["]|oncanplaythrough=[\'](.*?)[\']|oncuechange=["](.*?)["]|oncuechange=[\'](.*?)[\']|ondurationchange=["](.*?)["]|ondurationchange=[\'](.*?)[\']|onemptied=["](.*?)["]|onemptied=[\'](.*?)[\']|onended=["](.*?)["]|onended=[\'](.*?)[\']|onerror=["](.*?)["]|onerror=[\'](.*?)[\']|onloadeddata=["](.*?)["]|onloadeddata=[\'](.*?)[\']|onloadedmetadata=["](.*?)["]|onloadedmetadata=[\'](.*?)[\']|onloadstart=["](.*?)["]|onloadstart=[\'](.*?)[\']|onpause=["](.*?)["]|onpause=[\'](.*?)[\']|onplay=["](.*?)["]|onplay=[\'](.*?)[\']|onplaying=["](.*?)["]|onplaying=[\'](.*?)[\']|onprogress=["](.*?)["]|onprogress=[\'](.*?)[\']|onratechange=["](.*?)["]|onratechange=[\'](.*?)[\']|onseeked=["](.*?)["]|onseeked=[\'](.*?)[\']|onseeking=["](.*?)["]|onseeking=[\'](.*?)[\']|onstalled=["](.*?)["]|onstalled=[\'](.*?)[\']|onsuspend=["](.*?)["]|onsuspend=[\'](.*?)[\']|ontimeupdate=["](.*?)["]|ontimeupdate=[\'](.*?)[\']|onvolumechange=["](.*?)["]|onvolumechange=[\'](.*?)[\']|onwaiting=["](.*?)["]|onwaiting=[\'](.*?)[\']|ontoggle=["](.*?)["]|ontoggle=[\'](.*?)[\'])/m';
$wo["website_modes_off"]  = array(
    "facebook" => array(),
    "linkedin" => array(
        "poke_system",
        "games",
        "classified",
        "movies",
        "user_status",
        "common_things",
        "offer_system",
        "memories_system",
        "shout_box_system"
    ),
    "instagram" => array(
        "poke_system",
        "games",
        "movies",
        "common_things",
        "memories_system",
        "events",
        "blogs",
        "job_system",
        "funding_system",
        "pages",
        "groups",
        "forum",
        "offer_system",
        "nearby_business_system",
        "blog_approval",
        "audio_upload",
        "post_feelings",
        "post_location",
        "fileSharing",
        "shout_box_system",
        "post_poll"
    ),
    "twitter" => array(
        "poke_system",
        "games",
        "movies",
        "common_things",
        "memories_system",
        "events",
        "blogs",
        "job_system",
        "funding_system",
        "classified",
        "user_status",
        "offer_system",
        "shout_box_system",
        "post_feelings",
        "audio_upload",
        "post_feelings",
        "fileSharing",
        "pages",
        "groups"
    ),
    "askfm" => array(
        "poke_system",
        "games",
        "movies",
        "common_things",
        "memories_system",
        "events",
        "blogs",
        "job_system",
        "funding_system",
        "classified",
        "user_status",
        "offer_system",
        "forum",
        "pages",
        "groups",
        "stickers",
        "nearby_business_system",
        "stickers_system",
        "nearby_shop_system",
        "gift_system",
        "blog_approval",
        "fileSharing",
        "video_upload",
        "audio_upload",
        "second_post_button",
        "pro",
        "refund_system",
        "post_location",
        "post_feelings"
    ),
    "patreon" => array(
        "poke_system",
        "games",
        "movies",
        "common_things",
        "memories_system",
        "events",
        "blogs",
        "job_system",
        "funding_system",
        "classified",
        "user_status",
        "offer_system",
        "shout_box_system",
        "post_feelings",
        "post_feelings",
        "fileSharing",
        "pages",
        "groups",
        "forum",
        "post_location",
        "post_poll",
        "stickers"
    )
);
$wo["employment_type"]    = array(
    "1" => "full_time",
    "2" => "part_time",
    "3" => "self_employed",
    "4" => "freelance",
    "5" => "contract",
    "6" => "internship",
    "7" => "apprenticeship",
    "8" => "seasonal"
);
?>
